authorName: Unknown
experimentName: enas_macro
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 1
#choice: local, remote
trainingServicePlatform: local
#choice: true, false
useAnnotation: true
multiPhase: true
tuner:
  codeDir: ../general_controller
  classFileName: RL_tuner.py
  className: RLTuner
  classArgs:
    child_steps: 350
    controller_steps: 50

trial:
  command: sh ./macro_cifar10.sh
  codeDir: ./
  gpuNum: 1

